[package]
name = "maybenot-simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
priority-queue = "1.2.3"
maybenot = { path = "/home/pulls/Documents/maybenot/maybenot/" }
log = "0.4.17"
test-log = "0.2.11"
fastrand = "1.8.0"

[dev-dependencies]
env_logger = "*"
